# Используем минимальный образ Python
FROM python:3.11-slim-bullseye

# Устанавливаем системные зависимости для сборки и PostgreSQL
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Создаем рабочую директорию
WORKDIR /app

# Копируем файл зависимостей
COPY requirements.txt .

# Обновляем pip и устанавливаем зависимости
RUN python -m pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

# Копируем весь проект в контейнер
COPY . .

# Устанавливаем переменную окружения для Python
ENV PYTHONPATH=/app

# Запускаем бота
CMD ["python", "run.py"]
